import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'vi' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  formatCurrency: (amount: number) => string;
  formatDate: (date: Date) => string;
  formatNumber: (num: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation data - Hoàn chỉnh cho tất cả nội dung
const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.home': 'Home',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.help': 'Help',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.selectLanguage': 'Select Language',

    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.cart': 'Cart',
    'nav.account': 'Account',
    'nav.admin': 'Admin Panel',
    'nav.dashboard': 'Dashboard',

    // Homepage Content
    'home.hero.title': 'Discover Premium Electronics',
    'home.hero.subtitle': 'Experience the future of technology with our curated collection of premium electronics, designed to elevate your digital lifestyle.',
    'home.hero.shopNow': 'Shop Now',
    'home.hero.learnMore': 'Learn More',
    'home.features.title': 'Why Choose EliteStore?',
    'home.features.subtitle': 'We\'re committed to providing you with the best shopping experience and premium quality products.',
    'home.features.quality.title': 'Premium Quality',
    'home.features.quality.desc': 'Only the finest products from trusted brands make it to our collection.',
    'home.features.shipping.title': 'Fast Shipping',
    'home.features.shipping.desc': 'Free delivery on orders over $100. Express shipping available nationwide.',
    'home.features.support.title': '24/7 Support',
    'home.features.support.desc': 'Our expert team is here to help you with any questions or concerns.',
    'home.features.warranty.title': 'Warranty',
    'home.features.warranty.desc': 'All products come with comprehensive warranty and satisfaction guarantee.',

    // Products
    'products.title': 'Products',
    'products.featured': 'Featured Products',
    'products.new': 'New Products',
    'products.bestsellers': 'Best Sellers',
    'products.onSale': 'On Sale',
    'products.addToCart': 'Add to Cart',
    'products.buyNow': 'Buy Now',
    'products.outOfStock': 'Out of Stock',
    'products.inStock': 'In Stock',
    'products.price': 'Price',
    'products.originalPrice': 'Original Price',
    'products.discount': 'Discount',
    'products.rating': 'Rating',
    'products.reviews': 'Reviews',
    'products.description': 'Description',
    'products.specifications': 'Specifications',
    'products.features': 'Features',
    'products.category': 'Category',
    'products.brand': 'Brand',
    'products.model': 'Model',
    'products.color': 'Color',
    'products.size': 'Size',
    'products.quantity': 'Quantity',
    'products.availability': 'Availability',
    'products.shipping': 'Shipping',
    'products.warranty': 'Warranty',
    'products.returnPolicy': 'Return Policy',
    'products.relatedProducts': 'Related Products',
    'products.recentlyViewed': 'Recently Viewed',
    'products.compare': 'Compare',
    'products.wishlist': 'Wishlist',
    'products.share': 'Share',
    'products.searchPlaceholder': 'Search products...',
    'products.noResults': 'No products found',
    'products.sortBy': 'Sort by',
    'products.sortByName': 'Name',
    'products.sortByPrice': 'Price',
    'products.sortByRating': 'Rating',
    'products.sortByNewest': 'Newest',
    'products.filterByCategory': 'Filter by Category',
    'products.filterByPrice': 'Filter by Price',
    'products.filterByBrand': 'Filter by Brand',
    'products.priceRange': 'Price Range',
    'products.minPrice': 'Min Price',
    'products.maxPrice': 'Max Price',
    'products.showingResults': 'Showing {count} of {total} products',

    // Shopping Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.emptyMessage': 'Looks like you haven\'t added any items to your cart yet.',
    'cart.items': 'Items',
    'cart.item': 'Item',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.tax': 'Tax',
    'cart.shipping': 'Shipping',
    'cart.discount': 'Discount',
    'cart.coupon': 'Coupon',
    'cart.applyCoupon': 'Apply Coupon',
    'cart.removeCoupon': 'Remove Coupon',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.updateCart': 'Update Cart',
    'cart.removeItem': 'Remove Item',
    'cart.moveToWishlist': 'Move to Wishlist',
    'cart.saveForLater': 'Save for Later',
    'cart.estimatedTotal': 'Estimated Total',
    'cart.freeShipping': 'Free Shipping',
    'cart.freeShippingThreshold': 'Add {amount} more for free shipping',
    'cart.secureCheckout': 'Secure checkout with SSL encryption',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.billingInfo': 'Billing Information',
    'checkout.paymentInfo': 'Payment Information',
    'checkout.orderSummary': 'Order Summary',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.zipCode': 'ZIP Code',
    'checkout.country': 'Country',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.creditCard': 'Credit Card',
    'checkout.debitCard': 'Debit Card',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Bank Transfer',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.codDescription': 'Pay when you receive the order',
    'checkout.cardNumber': 'Card Number',
    'checkout.expiryDate': 'Expiry Date',
    'checkout.cvv': 'CVV',
    'checkout.cardholderName': 'Cardholder Name',
    'checkout.billingAddress': 'Billing Address',
    'checkout.sameAsShipping': 'Same as shipping address',
    'checkout.orderNotes': 'Order Notes',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.orderConfirmation': 'Order Confirmation',
    'checkout.thankYou': 'Thank you for your order!',
    'checkout.orderNumber': 'Order Number',
    'checkout.estimatedDelivery': 'Estimated Delivery',
    'checkout.trackOrder': 'Track Order',
    'checkout.orderConfirmed': 'Order Confirmed!',
    'checkout.orderSuccess': 'Your order has been successfully placed.',
    'checkout.continueShoppingBtn': 'Continue Shopping',
    'checkout.viewOrdersBtn': 'View Orders',

    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signOut': 'Sign Out',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome Back',
    'auth.joinUs': 'Join Us',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.rememberMe': 'Remember Me',
    'auth.agreeToTerms': 'I agree to the Terms and Conditions',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.accountCreated': 'Account created successfully',
    'auth.passwordReset': 'Password reset email sent',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.emailInvalid': 'Please enter a valid email address',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.demoCredentials': 'Demo Credentials:',
    'auth.adminDemo': 'Admin: admin@elitestore.com / admin123',
    'auth.customerDemo': 'Customer: Any email / password (6+ chars)',

    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.customers': 'Customers',
    'admin.analytics': 'Analytics',
    'admin.content': 'Content',
    'admin.marketing': 'Marketing',
    'admin.settings': 'Settings',
    'admin.users': 'Users',
    'admin.reports': 'Reports',
    'admin.inventory': 'Inventory',
    'admin.categories': 'Categories',
    'admin.brands': 'Brands',
    'admin.coupons': 'Coupons',
    'admin.campaigns': 'Campaigns',
    'admin.reviews': 'Reviews',
    'admin.shipping': 'Shipping',
    'admin.taxes': 'Taxes',
    'admin.payments': 'Payments',
    'admin.notifications': 'Notifications',
    'admin.backups': 'Backups',
    'admin.logs': 'Logs',
    'admin.security': 'Security',
    'admin.performance': 'Performance',
    'admin.maintenance': 'Maintenance',
    'admin.welcomeMessage': 'Welcome back! Here\'s what\'s happening with your store.',
    'admin.totalRevenue': 'Total Revenue',
    'admin.totalOrders': 'Total Orders',
    'admin.totalProducts': 'Total Products',
    'admin.totalCustomers': 'Total Customers',

    // Categories
    'categories.electronics': 'Electronics',
    'categories.wearables': 'Wearables',
    'categories.photography': 'Photography',
    'categories.gaming': 'Gaming',
    'categories.computers': 'Computers',
    'categories.smartphones': 'Smartphones',
    'categories.tablets': 'Tablets',
    'categories.audio': 'Audio',
    'categories.accessories': 'Accessories',

    // Footer
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.blog': 'Blog',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.contactUs': 'Contact Us',
    'footer.shipping': 'Shipping',
    'footer.returns': 'Returns',
    'footer.sizeGuide': 'Size Guide',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.followUs': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'Subscribe',
    'footer.enterEmail': 'Enter your email',
    'footer.allRightsReserved': 'All rights reserved',
    'footer.copyright': '© 2024 EliteStore. All rights reserved.',

    // Testimonials
    'testimonials.title': 'What Our Customers Say',
    'testimonials.subtitle': 'Don\'t just take our word for it. Here\'s what our satisfied customers have to say about their experience.',
    'testimonials.customer1.name': 'Sarah Johnson',
    'testimonials.customer1.role': 'Tech Enthusiast',
    'testimonials.customer1.text': 'Amazing quality products and exceptional customer service. The 3D product viewer helped me make the perfect choice!',
    'testimonials.customer2.name': 'Michael Chen',
    'testimonials.customer2.role': 'Professional Photographer',
    'testimonials.customer2.text': 'The camera equipment I ordered exceeded my expectations. Fast shipping and excellent packaging. Highly recommended!',
    'testimonials.customer3.name': 'Emily Rodriguez',
    'testimonials.customer3.role': 'Fitness Coach',
    'testimonials.customer3.text': 'Love my new fitness watch! The features are incredible and the battery life is exactly as advertised. Great value!',

    // Newsletter
    'newsletter.title': 'Stay Updated with Latest Deals',
    'newsletter.subtitle': 'Subscribe to our newsletter and be the first to know about new products, exclusive offers, and special promotions.',
    'newsletter.subscribing': 'Subscribing...',
    'newsletter.thankYou': 'Thank you for subscribing!',
    'newsletter.privacy': 'We respect your privacy. Unsubscribe at any time.',

    // Product Details
    'productDetail.backToProducts': 'Back to Products',
    'productDetail.productNotFound': 'Product not found',
    'productDetail.keyFeatures': 'Key Features',
    'productDetail.noReviews': 'No reviews yet',
    'productDetail.beFirstReview': 'Be the first to review this product!',
    'productDetail.dragToRotate': '360° View - Drag to rotate',
    'productDetail.warranty': 'Warranty',
    'productDetail.freeShipping': 'Free Shipping',
    'productDetail.dayReturn': '30-Day Return',

    // Notifications
    'notifications.itemAdded': 'Added to Cart',
    'notifications.itemAddedMessage': '{productName} has been added to your cart.',
    'notifications.orderPlaced': 'Order Placed Successfully',
    'notifications.orderPlacedMessage': 'Your order has been confirmed and will be processed shortly.',
  },

  vi: {
    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Đã xảy ra lỗi',
    'common.success': 'Thành công',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.save': 'Lưu',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.view': 'Xem',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.sort': 'Sắp xếp',
    'common.next': 'Tiếp theo',
    'common.previous': 'Trước',
    'common.close': 'Đóng',
    'common.submit': 'Gửi',
    'common.reset': 'Đặt lại',
    'common.clear': 'Xóa',
    'common.select': 'Chọn',
    'common.all': 'Tất cả',
    'common.none': 'Không có',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.ok': 'OK',
    'common.back': 'Quay lại',
    'common.continue': 'Tiếp tục',
    'common.finish': 'Hoàn thành',
    'common.home': 'Trang chủ',
    'common.about': 'Giới thiệu',
    'common.contact': 'Liên hệ',
    'common.help': 'Trợ giúp',
    'common.settings': 'Cài đặt',
    'common.profile': 'Hồ sơ',
    'common.logout': 'Đăng xuất',
    'common.login': 'Đăng nhập',
    'common.register': 'Đăng ký',
    'common.selectLanguage': 'Chọn ngôn ngữ',

    // Navigation
    'nav.home': 'Trang chủ',
    'nav.products': 'Sản phẩm',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.cart': 'Giỏ hàng',
    'nav.account': 'Tài khoản',
    'nav.admin': 'Quản trị viên',
    'nav.dashboard': 'Bảng điều khiển',

    // Homepage Content
    'home.hero.title': 'Khám Phá Điện Tử Cao Cấp',
    'home.hero.subtitle': 'Trải nghiệm tương lai của công nghệ với bộ sưu tập điện tử cao cấp được tuyển chọn, được thiết kế để nâng cao lối sống số của bạn.',
    'home.hero.shopNow': 'Mua Ngay',
    'home.hero.learnMore': 'Tìm Hiểu Thêm',
    'home.features.title': 'Tại Sao Chọn EliteStore?',
    'home.features.subtitle': 'Chúng tôi cam kết mang đến cho bạn trải nghiệm mua sắm tốt nhất và các sản phẩm chất lượng cao cấp.',
    'home.features.quality.title': 'Chất Lượng Cao Cấp',
    'home.features.quality.desc': 'Chỉ những sản phẩm tốt nhất từ các thương hiệu uy tín mới có mặt trong bộ sưu tập của chúng tôi.',
    'home.features.shipping.title': 'Giao Hàng Nhanh',
    'home.features.shipping.desc': 'Miễn phí giao hàng cho đơn hàng trên 2.500.000đ. Giao hàng nhanh trên toàn quốc.',
    'home.features.support.title': 'Hỗ Trợ 24/7',
    'home.features.support.desc': 'Đội ngũ chuyên gia của chúng tôi luôn sẵn sàng giúp bạn với mọi câu hỏi hoặc thắc mắc.',
    'home.features.warranty.title': 'Bảo Hành',
    'home.features.warranty.desc': 'Tất cả sản phẩm đều có bảo hành toàn diện và đảm bảo sự hài lòng.',

    // Products
    'products.title': 'Sản phẩm',
    'products.featured': 'Sản phẩm nổi bật',
    'products.new': 'Sản phẩm mới',
    'products.bestsellers': 'Bán chạy nhất',
    'products.onSale': 'Đang giảm giá',
    'products.addToCart': 'Thêm vào giỏ',
    'products.buyNow': 'Mua ngay',
    'products.outOfStock': 'Hết hàng',
    'products.inStock': 'Còn hàng',
    'products.price': 'Giá',
    'products.originalPrice': 'Giá gốc',
    'products.discount': 'Giảm giá',
    'products.rating': 'Đánh giá',
    'products.reviews': 'Nhận xét',
    'products.description': 'Mô tả',
    'products.specifications': 'Thông số kỹ thuật',
    'products.features': 'Tính năng',
    'products.category': 'Danh mục',
    'products.brand': 'Thương hiệu',
    'products.model': 'Mẫu',
    'products.color': 'Màu sắc',
    'products.size': 'Kích thước',
    'products.quantity': 'Số lượng',
    'products.availability': 'Tình trạng',
    'products.shipping': 'Vận chuyển',
    'products.warranty': 'Bảo hành',
    'products.returnPolicy': 'Chính sách đổi trả',
    'products.relatedProducts': 'Sản phẩm liên quan',
    'products.recentlyViewed': 'Đã xem gần đây',
    'products.compare': 'So sánh',
    'products.wishlist': 'Yêu thích',
    'products.share': 'Chia sẻ',
    'products.searchPlaceholder': 'Tìm kiếm sản phẩm...',
    'products.noResults': 'Không tìm thấy sản phẩm',
    'products.sortBy': 'Sắp xếp theo',
    'products.sortByName': 'Tên',
    'products.sortByPrice': 'Giá',
    'products.sortByRating': 'Đánh giá',
    'products.sortByNewest': 'Mới nhất',
    'products.filterByCategory': 'Lọc theo danh mục',
    'products.filterByPrice': 'Lọc theo giá',
    'products.filterByBrand': 'Lọc theo thương hiệu',
    'products.priceRange': 'Khoảng giá',
    'products.minPrice': 'Giá tối thiểu',
    'products.maxPrice': 'Giá tối đa',
    'products.showingResults': 'Hiển thị {count} trong số {total} sản phẩm',

    // Shopping Cart
    'cart.title': 'Giỏ hàng',
    'cart.empty': 'Giỏ hàng của bạn đang trống',
    'cart.emptyMessage': 'Có vẻ như bạn chưa thêm sản phẩm nào vào giỏ hàng.',
    'cart.items': 'Sản phẩm',
    'cart.item': 'Sản phẩm',
    'cart.subtotal': 'Tạm tính',
    'cart.total': 'Tổng cộng',
    'cart.tax': 'Thuế',
    'cart.shipping': 'Phí vận chuyển',
    'cart.discount': 'Giảm giá',
    'cart.coupon': 'Mã giảm giá',
    'cart.applyCoupon': 'Áp dụng mã',
    'cart.removeCoupon': 'Xóa mã',
    'cart.checkout': 'Thanh toán',
    'cart.continueShopping': 'Tiếp tục mua sắm',
    'cart.updateCart': 'Cập nhật giỏ hàng',
    'cart.removeItem': 'Xóa sản phẩm',
    'cart.moveToWishlist': 'Chuyển vào yêu thích',
    'cart.saveForLater': 'Lưu để mua sau',
    'cart.estimatedTotal': 'Tổng ước tính',
    'cart.freeShipping': 'Miễn phí vận chuyển',
    'cart.freeShippingThreshold': 'Thêm {amount} để được miễn phí vận chuyển',
    'cart.secureCheckout': 'Thanh toán bảo mật với mã hóa SSL',

    // Checkout
    'checkout.title': 'Thanh toán',
    'checkout.shippingInfo': 'Thông tin giao hàng',
    'checkout.billingInfo': 'Thông tin thanh toán',
    'checkout.paymentInfo': 'Phương thức thanh toán',
    'checkout.orderSummary': 'Tóm tắt đơn hàng',
    'checkout.firstName': 'Họ',
    'checkout.lastName': 'Tên',
    'checkout.email': 'Email',
    'checkout.phone': 'Số điện thoại',
    'checkout.address': 'Địa chỉ',
    'checkout.city': 'Thành phố',
    'checkout.state': 'Tỉnh/Thành',
    'checkout.zipCode': 'Mã bưu điện',
    'checkout.country': 'Quốc gia',
    'checkout.paymentMethod': 'Phương thức thanh toán',
    'checkout.creditCard': 'Thẻ tín dụng',
    'checkout.debitCard': 'Thẻ ghi nợ',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': 'Chuyển khoản ngân hàng',
    'checkout.cashOnDelivery': 'Thanh toán khi nhận hàng',
    'checkout.codDescription': 'Thanh toán khi bạn nhận được đơn hàng',
    'checkout.cardNumber': 'Số thẻ',
    'checkout.expiryDate': 'Ngày hết hạn',
    'checkout.cvv': 'CVV',
    'checkout.cardholderName': 'Tên chủ thẻ',
    'checkout.billingAddress': 'Địa chỉ thanh toán',
    'checkout.sameAsShipping': 'Giống địa chỉ giao hàng',
    'checkout.orderNotes': 'Ghi chú đơn hàng',
    'checkout.placeOrder': 'Đặt hàng',
    'checkout.processing': 'Đang xử lý...',
    'checkout.orderConfirmation': 'Xác nhận đơn hàng',
    'checkout.thankYou': 'Cảm ơn bạn đã đặt hàng!',
    'checkout.orderNumber': 'Mã đơn hàng',
    'checkout.estimatedDelivery': 'Dự kiến giao hàng',
    'checkout.trackOrder': 'Theo dõi đơn hàng',
    'checkout.orderConfirmed': 'Đơn hàng đã được xác nhận!',
    'checkout.orderSuccess': 'Đơn hàng của bạn đã được đặt thành công.',
    'checkout.continueShoppingBtn': 'Tiếp tục mua sắm',
    'checkout.viewOrdersBtn': 'Xem đơn hàng',

    // Authentication
    'auth.signIn': 'Đăng nhập',
    'auth.signUp': 'Đăng ký',
    'auth.signOut': 'Đăng xuất',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.resetPassword': 'Đặt lại mật khẩu',
    'auth.createAccount': 'Tạo tài khoản',
    'auth.welcomeBack': 'Chào mừng trở lại',
    'auth.joinUs': 'Tham gia với chúng tôi',
    'auth.emailAddress': 'Địa chỉ email',
    'auth.password': 'Mật khẩu',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.fullName': 'Họ và tên',
    'auth.rememberMe': 'Ghi nhớ đăng nhập',
    'auth.agreeToTerms': 'Tôi đồng ý với Điều khoản và Điều kiện',
    'auth.alreadyHaveAccount': 'Đã có tài khoản?',
    'auth.dontHaveAccount': 'Chưa có tài khoản?',
    'auth.invalidCredentials': 'Email hoặc mật khẩu không đúng',
    'auth.accountCreated': 'Tài khoản đã được tạo thành công',
    'auth.passwordReset': 'Email đặt lại mật khẩu đã được gửi',
    'auth.emailRequired': 'Email là bắt buộc',
    'auth.passwordRequired': 'Mật khẩu là bắt buộc',
    'auth.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
    'auth.emailInvalid': 'Vui lòng nhập địa chỉ email hợp lệ',
    'auth.passwordMismatch': 'Mật khẩu không khớp',
    'auth.demoCredentials': 'Tài khoản demo:',
    'auth.adminDemo': 'Quản trị: admin@elitestore.com / admin123',
    'auth.customerDemo': 'Khách hàng: Email bất kỳ / mật khẩu (6+ ký tự)',

    // Admin
    'admin.dashboard': 'Bảng điều khiển',
    'admin.products': 'Sản phẩm',
    'admin.orders': 'Đơn hàng',
    'admin.customers': 'Khách hàng',
    'admin.analytics': 'Phân tích',
    'admin.content': 'Nội dung',
    'admin.marketing': 'Marketing',
    'admin.settings': 'Cài đặt',
    'admin.users': 'Người dùng',
    'admin.reports': 'Báo cáo',
    'admin.inventory': 'Kho hàng',
    'admin.categories': 'Danh mục',
    'admin.brands': 'Thương hiệu',
    'admin.coupons': 'Mã giảm giá',
    'admin.campaigns': 'Chiến dịch',
    'admin.reviews': 'Đánh giá',
    'admin.shipping': 'Vận chuyển',
    'admin.taxes': 'Thuế',
    'admin.payments': 'Thanh toán',
    'admin.notifications': 'Thông báo',
    'admin.backups': 'Sao lưu',
    'admin.logs': 'Nhật ký',
    'admin.security': 'Bảo mật',
    'admin.performance': 'Hiệu suất',
    'admin.maintenance': 'Bảo trì',
    'admin.welcomeMessage': 'Chào mừng trở lại! Đây là những gì đang diễn ra với cửa hàng của bạn.',
    'admin.totalRevenue': 'Tổng doanh thu',
    'admin.totalOrders': 'Tổng đơn hàng',
    'admin.totalProducts': 'Tổng sản phẩm',
    'admin.totalCustomers': 'Tổng khách hàng',

    // Categories
    'categories.electronics': 'Điện tử',
    'categories.wearables': 'Thiết bị đeo',
    'categories.photography': 'Nhiếp ảnh',
    'categories.gaming': 'Game',
    'categories.computers': 'Máy tính',
    'categories.smartphones': 'Điện thoại',
    'categories.tablets': 'Máy tính bảng',
    'categories.audio': 'Âm thanh',
    'categories.accessories': 'Phụ kiện',

    // Footer
    'footer.company': 'Công ty',
    'footer.aboutUs': 'Về chúng tôi',
    'footer.careers': 'Tuyển dụng',
    'footer.press': 'Báo chí',
    'footer.blog': 'Blog',
    'footer.support': 'Hỗ trợ',
    'footer.helpCenter': 'Trung tâm trợ giúp',
    'footer.contactUs': 'Liên hệ',
    'footer.shipping': 'Vận chuyển',
    'footer.returns': 'Đổi trả',
    'footer.sizeGuide': 'Hướng dẫn kích thước',
    'footer.legal': 'Pháp lý',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.cookies': 'Chính sách cookie',
    'footer.followUs': 'Theo dõi chúng tôi',
    'footer.newsletter': 'Bản tin',
    'footer.subscribe': 'Đăng ký',
    'footer.enterEmail': 'Nhập email của bạn',
    'footer.allRightsReserved': 'Tất cả quyền được bảo lưu',
    'footer.copyright': '© 2024 EliteStore. Tất cả quyền được bảo lưu.',

    // Testimonials
    'testimonials.title': 'Khách Hàng Nói Gì Về Chúng Tôi',
    'testimonials.subtitle': 'Đừng chỉ tin lời chúng tôi. Đây là những gì khách hàng hài lòng của chúng tôi nói về trải nghiệm của họ.',
    'testimonials.customer1.name': 'Nguyễn Thị Hoa',
    'testimonials.customer1.role': 'Chuyên gia Công nghệ',
    'testimonials.customer1.text': 'Sản phẩm chất lượng tuyệt vời và dịch vụ khách hàng đặc biệt. Trình xem sản phẩm 3D đã giúp tôi đưa ra lựa chọn hoàn hảo!',
    'testimonials.customer2.name': 'Trần Văn Minh',
    'testimonials.customer2.role': 'Nhiếp ảnh gia Chuyên nghiệp',
    'testimonials.customer2.text': 'Thiết bị máy ảnh tôi đặt hàng vượt quá mong đợi của tôi. Giao hàng nhanh và đóng gói tuyệt vời. Rất khuyến khích!',
    'testimonials.customer3.name': 'Lê Thị Mai',
    'testimonials.customer3.role': 'Huấn luyện viên Thể dục',
    'testimonials.customer3.text': 'Yêu chiếc đồng hồ thể dục mới của tôi! Các tính năng thật tuyệt vời và thời lượng pin chính xác như quảng cáo. Giá trị tuyệt vời!',

    // Newsletter
    'newsletter.title': 'Cập Nhật Những Ưu Đãi Mới Nhất',
    'newsletter.subtitle': 'Đăng ký bản tin của chúng tôi và là người đầu tiên biết về sản phẩm mới, ưu đãi độc quyền và khuyến mãi đặc biệt.',
    'newsletter.subscribing': 'Đang đăng ký...',
    'newsletter.thankYou': 'Cảm ơn bạn đã đăng ký!',
    'newsletter.privacy': 'Chúng tôi tôn trọng quyền riêng tư của bạn. Hủy đăng ký bất cứ lúc nào.',

    // Product Details
    'productDetail.backToProducts': 'Quay lại Sản phẩm',
    'productDetail.productNotFound': 'Không tìm thấy sản phẩm',
    'productDetail.keyFeatures': 'Tính Năng Chính',
    'productDetail.noReviews': 'Chưa có đánh giá',
    'productDetail.beFirstReview': 'Hãy là người đầu tiên đánh giá sản phẩm này!',
    'productDetail.dragToRotate': 'Xem 360° - Kéo để xoay',
    'productDetail.warranty': 'Bảo hành',
    'productDetail.freeShipping': 'Miễn phí vận chuyển',
    'productDetail.dayReturn': 'Đổi trả trong 30 ngày',

    // Notifications
    'notifications.itemAdded': 'Đã thêm vào giỏ hàng',
    'notifications.itemAddedMessage': '{productName} đã được thêm vào giỏ hàng của bạn.',
    'notifications.orderPlaced': 'Đặt hàng thành công',
    'notifications.orderPlacedMessage': 'Đơn hàng của bạn đã được xác nhận và sẽ được xử lý sớm.',
  },

  zh: {
    // Common
    'common.loading': '加载中...',
    'common.error': '发生错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.view': '查看',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.next': '下一个',
    'common.previous': '上一个',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.clear': '清除',
    'common.select': '选择',
    'common.all': '全部',
    'common.none': '无',
    'common.yes': '是',
    'common.no': '否',
    'common.ok': '确定',
    'common.back': '返回',
    'common.continue': '继续',
    'common.finish': '完成',
    'common.home': '首页',
    'common.about': '关于',
    'common.contact': '联系',
    'common.help': '帮助',
    'common.settings': '设置',
    'common.profile': '个人资料',
    'common.logout': '退出',
    'common.login': '登录',
    'common.register': '注册',
    'common.selectLanguage': '选择语言',

    // Navigation
    'nav.home': '首页',
    'nav.products': '产品',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.cart': '购物车',
    'nav.account': '账户',
    'nav.admin': '管理员',
    'nav.dashboard': '仪表板',

    // Homepage Content
    'home.hero.title': '探索高端电子产品',
    'home.hero.subtitle': '通过我们精心挑选的高端电子产品系列体验技术的未来，旨在提升您的数字生活方式。',
    'home.hero.shopNow': '立即购买',
    'home.hero.learnMore': '了解更多',
    'home.features.title': '为什么选择EliteStore？',
    'home.features.subtitle': '我们致力于为您提供最佳的购物体验和优质产品。',
    'home.features.quality.title': '优质品质',
    'home.features.quality.desc': '只有来自可信品牌的最优质产品才能进入我们的收藏。',
    'home.features.shipping.title': '快速配送',
    'home.features.shipping.desc': '订单满¥800免费配送。全国范围内提供快递服务。',
    'home.features.support.title': '24/7支持',
    'home.features.support.desc': '我们的专家团队随时为您解答任何问题或疑虑。',
    'home.features.warranty.title': '保修',
    'home.features.warranty.desc': '所有产品都提供全面保修和满意度保证。',

    // Products
    'products.title': '产品',
    'products.featured': '精选产品',
    'products.new': '新品',
    'products.bestsellers': '热销产品',
    'products.onSale': '促销中',
    'products.addToCart': '加入购物车',
    'products.buyNow': '立即购买',
    'products.outOfStock': '缺货',
    'products.inStock': '有库存',
    'products.price': '价格',
    'products.originalPrice': '原价',
    'products.discount': '折扣',
    'products.rating': '评分',
    'products.reviews': '评论',
    'products.description': '描述',
    'products.specifications': '规格',
    'products.features': '特性',
    'products.category': '类别',
    'products.brand': '品牌',
    'products.model': '型号',
    'products.color': '颜色',
    'products.size': '尺寸',
    'products.quantity': '数量',
    'products.availability': '可用性',
    'products.shipping': '运输',
    'products.warranty': '保修',
    'products.returnPolicy': '退货政策',
    'products.relatedProducts': '相关产品',
    'products.recentlyViewed': '最近查看',
    'products.compare': '比较',
    'products.wishlist': '愿望清单',
    'products.share': '分享',
    'products.searchPlaceholder': '搜索产品...',
    'products.noResults': '未找到产品',
    'products.sortBy': '排序方式',
    'products.sortByName': '名称',
    'products.sortByPrice': '价格',
    'products.sortByRating': '评分',
    'products.sortByNewest': '最新',
    'products.filterByCategory': '按类别筛选',
    'products.filterByPrice': '按价格筛选',
    'products.filterByBrand': '按品牌筛选',
    'products.priceRange': '价格范围',
    'products.minPrice': '最低价格',
    'products.maxPrice': '最高价格',
    'products.showingResults': '显示 {count} 个，共 {total} 个产品',

    // Shopping Cart
    'cart.title': '购物车',
    'cart.empty': '您的购物车是空的',
    'cart.emptyMessage': '看起来您还没有在购物车中添加任何商品。',
    'cart.items': '商品',
    'cart.item': '商品',
    'cart.subtotal': '小计',
    'cart.total': '总计',
    'cart.tax': '税费',
    'cart.shipping': '运费',
    'cart.discount': '折扣',
    'cart.coupon': '优惠券',
    'cart.applyCoupon': '使用优惠券',
    'cart.removeCoupon': '移除优惠券',
    'cart.checkout': '结账',
    'cart.continueShopping': '继续购物',
    'cart.updateCart': '更新购物车',
    'cart.removeItem': '移除商品',
    'cart.moveToWishlist': '移至愿望清单',
    'cart.saveForLater': '保存以备后用',
    'cart.estimatedTotal': '预计总额',
    'cart.freeShipping': '免费送货',
    'cart.freeShippingThreshold': '再购买 {amount} 即可免费送货',
    'cart.secureCheckout': '使用SSL加密的安全结账',

    // Checkout
    'checkout.title': '结账',
    'checkout.shippingInfo': '配送信息',
    'checkout.billingInfo': '账单信息',
    'checkout.paymentInfo': '支付信息',
    'checkout.orderSummary': '订单摘要',
    'checkout.firstName': '名',
    'checkout.lastName': '姓',
    'checkout.email': '邮箱',
    'checkout.phone': '电话',
    'checkout.address': '地址',
    'checkout.city': '城市',
    'checkout.state': '省/州',
    'checkout.zipCode': '邮政编码',
    'checkout.country': '国家',
    'checkout.paymentMethod': '支付方式',
    'checkout.creditCard': '信用卡',
    'checkout.debitCard': '借记卡',
    'checkout.paypal': 'PayPal',
    'checkout.bankTransfer': '银行转账',
    'checkout.cashOnDelivery': '货到付款',
    'checkout.codDescription': '收到订单时付款',
    'checkout.cardNumber': '卡号',
    'checkout.expiryDate': '到期日期',
    'checkout.cvv': 'CVV',
    'checkout.cardholderName': '持卡人姓名',
    'checkout.billingAddress': '账单地址',
    'checkout.sameAsShipping': '与配送地址相同',
    'checkout.orderNotes': '订单备注',
    'checkout.placeOrder': '下单',
    'checkout.processing': '处理中...',
    'checkout.orderConfirmation': '订单确认',
    'checkout.thankYou': '感谢您的订单！',
    'checkout.orderNumber': '订单号',
    'checkout.estimatedDelivery': '预计送达',
    'checkout.trackOrder': '跟踪订单',
    'checkout.orderConfirmed': '订单已确认！',
    'checkout.orderSuccess': '您的订单已成功下单。',
    'checkout.continueShoppingBtn': '继续购物',
    'checkout.viewOrdersBtn': '查看订单',

    // Authentication
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.signOut': '退出',
    'auth.forgotPassword': '忘记密码？',
    'auth.resetPassword': '重置密码',
    'auth.createAccount': '创建账户',
    'auth.welcomeBack': '欢迎回来',
    'auth.joinUs': '加入我们',
    'auth.emailAddress': '邮箱地址',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.fullName': '全名',
    'auth.rememberMe': '记住我',
    'auth.agreeToTerms': '我同意条款和条件',
    'auth.alreadyHaveAccount': '已有账户？',
    'auth.dontHaveAccount': '没有账户？',
    'auth.invalidCredentials': '邮箱或密码无效',
    'auth.accountCreated': '账户创建成功',
    'auth.passwordReset': '密码重置邮件已发送',
    'auth.emailRequired': '邮箱是必需的',
    'auth.passwordRequired': '密码是必需的',
    'auth.passwordTooShort': '密码至少需要6个字符',
    'auth.emailInvalid': '请输入有效的邮箱地址',
    'auth.passwordMismatch': '密码不匹配',
    'auth.demoCredentials': '演示账户：',
    'auth.adminDemo': '管理员：admin@elitestore.com / admin123',
    'auth.customerDemo': '客户：任意邮箱 / 密码（6+字符）',

    // Admin
    'admin.dashboard': '仪表板',
    'admin.products': '产品',
    'admin.orders': '订单',
    'admin.customers': '客户',
    'admin.analytics': '分析',
    'admin.content': '内容',
    'admin.marketing': '营销',
    'admin.settings': '设置',
    'admin.users': '用户',
    'admin.reports': '报告',
    'admin.inventory': '库存',
    'admin.categories': '类别',
    'admin.brands': '品牌',
    'admin.coupons': '优惠券',
    'admin.campaigns': '活动',
    'admin.reviews': '评论',
    'admin.shipping': '运输',
    'admin.taxes': '税费',
    'admin.payments': '支付',
    'admin.notifications': '通知',
    'admin.backups': '备份',
    'admin.logs': '日志',
    'admin.security': '安全',
    'admin.performance': '性能',
    'admin.maintenance': '维护',
    'admin.welcomeMessage': '欢迎回来！这是您商店的最新动态。',
    'admin.totalRevenue': '总收入',
    'admin.totalOrders': '总订单',
    'admin.totalProducts': '总产品',
    'admin.totalCustomers': '总客户',

    // Categories
    'categories.electronics': '电子产品',
    'categories.wearables': '可穿戴设备',
    'categories.photography': '摄影',
    'categories.gaming': '游戏',
    'categories.computers': '电脑',
    'categories.smartphones': '智能手机',
    'categories.tablets': '平板电脑',
    'categories.audio': '音频',
    'categories.accessories': '配件',

    // Footer
    'footer.company': '公司',
    'footer.aboutUs': '关于我们',
    'footer.careers': '招聘',
    'footer.press': '新闻',
    'footer.blog': '博客',
    'footer.support': '支持',
    'footer.helpCenter': '帮助中心',
    'footer.contactUs': '联系我们',
    'footer.shipping': '运输',
    'footer.returns': '退货',
    'footer.sizeGuide': '尺寸指南',
    'footer.legal': '法律',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.cookies': 'Cookie政策',
    'footer.followUs': '关注我们',
    'footer.newsletter': '通讯',
    'footer.subscribe': '订阅',
    'footer.enterEmail': '输入您的邮箱',
    'footer.allRightsReserved': '保留所有权利',
    'footer.copyright': '© 2024 EliteStore. 保留所有权利。',

    // Testimonials
    'testimonials.title': '客户评价',
    'testimonials.subtitle': '不要只听我们的话。以下是我们满意客户对他们体验的评价。',
    'testimonials.customer1.name': '王小明',
    'testimonials.customer1.role': '技术爱好者',
    'testimonials.customer1.text': '产品质量惊人，客户服务卓越。3D产品查看器帮助我做出了完美的选择！',
    'testimonials.customer2.name': '李华',
    'testimonials.customer2.role': '专业摄影师',
    'testimonials.customer2.text': '我订购的相机设备超出了我的期望。快速配送和优秀包装。强烈推荐！',
    'testimonials.customer3.name': '张美丽',
    'testimonials.customer3.role': '健身教练',
    'testimonials.customer3.text': '喜欢我的新健身手表！功能令人难以置信，电池续航正如广告所说。物超所值！',

    // Newsletter
    'newsletter.title': '获取最新优惠信息',
    'newsletter.subtitle': '订阅我们的通讯，第一时间了解新产品、独家优惠和特别促销。',
    'newsletter.subscribing': '订阅中...',
    'newsletter.thankYou': '感谢您的订阅！',
    'newsletter.privacy': '我们尊重您的隐私。随时可以取消订阅。',

    // Product Details
    'productDetail.backToProducts': '返回产品',
    'productDetail.productNotFound': '未找到产品',
    'productDetail.keyFeatures': '主要特性',
    'productDetail.noReviews': '暂无评论',
    'productDetail.beFirstReview': '成为第一个评论此产品的人！',
    'productDetail.dragToRotate': '360°视图 - 拖动旋转',
    'productDetail.warranty': '保修',
    'productDetail.freeShipping': '免费送货',
    'productDetail.dayReturn': '30天退货',

    // Notifications
    'notifications.itemAdded': '已添加到购物车',
    'notifications.itemAddedMessage': '{productName} 已添加到您的购物车。',
    'notifications.orderPlaced': '订单下单成功',
    'notifications.orderPlacedMessage': '您的订单已确认，将很快处理。',
  }
};

// Currency configurations
const currencyConfig = {
  en: { code: 'USD', symbol: '$', locale: 'en-US' },
  vi: { code: 'VND', symbol: '₫', locale: 'vi-VN' },
  zh: { code: 'CNY', symbol: '¥', locale: 'zh-CN' }
};

// Date format configurations
const dateConfig = {
  en: { locale: 'en-US', options: { year: 'numeric', month: 'long', day: 'numeric' } },
  vi: { locale: 'vi-VN', options: { year: 'numeric', month: 'long', day: 'numeric' } },
  zh: { locale: 'zh-CN', options: { year: 'numeric', month: 'long', day: 'numeric' } }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    
    // Update page direction for RTL languages (if needed in future)
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    
    // Update page title based on language
    const titles = {
      en: 'EliteStore - Premium Electronics & Technology',
      vi: 'EliteStore - Điện tử & Công nghệ Cao cấp',
      zh: 'EliteStore - 高端电子产品与技术'
    };
    document.title = titles[language];
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || translations.en[key] || key;
    
    // Replace parameters in translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, String(value));
      });
    }
    
    return translation;
  };

  const formatCurrency = (amount: number): string => {
    const config = currencyConfig[language];
    return new Intl.NumberFormat(config.locale, {
      style: 'currency',
      currency: config.code,
      minimumFractionDigits: 0,
      maximumFractionDigits: 2
    }).format(amount);
  };

  const formatDate = (date: Date): string => {
    const config = dateConfig[language];
    return new Intl.DateTimeFormat(config.locale, config.options as any).format(date);
  };

  const formatNumber = (num: number): string => {
    const config = currencyConfig[language];
    return new Intl.NumberFormat(config.locale).format(num);
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    formatCurrency,
    formatDate,
    formatNumber
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};